Fuzz 582 refactor config
CodeIntelligenceTesting/jazzer pull request #767
Opened 2023-06-14 17:56 UTC by fmeum

2023-06-15 16:48 UTC, TheCoryBarker commented on src/main/java/com/code_intelligence/jazzer/driver/Opt.java
> -  public static final String androidBootclassJarPath = stringSetting("android_bootclass_jar_path",
yes it's unused

2023-06-19 12:33 UTC, bertschneider commented on src/main/java/com/code_intelligence/jazzer/junit/AgentConfigurator.java
> +    Opt.instrumentationIncludes.setIfDefault(singletonList("**"));
Why set `instrumentationIncludes` here?

2023-06-19 12:49 UTC, bertschneider commented on src/main/java/com/code_intelligence/jazzer/driver/OptItem.java
> +     * Split value into non-empty takens separated by separator. Backslashes can be used to escape
Changed.

2023-06-19 12:50 UTC, bertschneider commented on src/main/java/com/code_intelligence/jazzer/driver/OptItem.java
> +    protected <T> IllegalOptionValueException(String message) {
Removed.

2023-06-19 13:18 UTC, bertschneider commented on src/main/java/com/code_intelligence/jazzer/junit/AgentConfigurator.java
> +    Opt.instrumentationIncludes.setIfDefault(singletonList("**"));
It shouldn't hurt, though. Ignore this for now.

2023-06-19 13:19 UTC, bertschneider commented on src/main/java/com/code_intelligence/jazzer/driver/OptItem.java
> +        .<Supplier<Stream<T>>>of(this::getFromManifest, this::getFromEnv, this::getFromProperties,
The rusulting code looks quite nice and more cleanly separated, it complicates CLI and JUnit configuration handling a little bit, though. Ignore it for now.

2023-06-19 13:20 UTC, bertschneider approved these changes

2023-06-19 14:02 UTC, br-lewis requested changes

2023-06-19 14:05 UTC, br-lewis commented on src/main/java/com/code_intelligence/jazzer/driver/OptItem.java
> +      return null;
I'll just change it to return `bool` for now. We'll probably want to clean it up later and have `OptItem.Bool` override `toString` to drop everything in the parens but that can be done in another PR.

2023-06-19 14:52 UTC, merged